#imagem base do node.js
FROM node:18-alpine

#Usuário não root
RUN addgroup -S app && adduser -S appuser -G appgroup

#Diretório de trabalho
WORKDIR /app

#Copia os arquivos do projeto

COPY package*.json ./

#Instala as dependencias
RUN npm install 

#Copia o restante dos arquivos
COPY . .

#Altera o usuario para não root
USER appuser

#Expoe a porta da aplicação
EXPOSE 3000

#Comando para iniciar aplicação
CMD [ "node", "server.js"]

