apiVersion: apps/v1
kind: Deployment
metadata:
  name: mari-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mari-app  
  template:
    metadata:
      labels:
        app: mari-app
    spec:
      containers :
      - name: mari-app
      image: projetojackexperts:latest
      ports:
      - containerPort : 3001
      env:
       - name : PAGE_CONTENT
       value: "Conteúdo da página"
       -name: USER_NAME
       value: "Usuário Exemplo"