apiVersion: apps/v1
kind: Deployment
metadata:
  name: mari-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mari-app  
  template:
    metadata:
      labels:
        app: mari-app
    spec:
      imagePullSecrets:
        - name: meu-secret-docker
      containers:
        - name: mari-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3001
          env:
            - name: PAGE_CONTENT
              value: {{ .Values.config.pageContent | quote }}
            - name: USER_NAME
              value: {{ .Values.config.userName | quote }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mari-app-ingress
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: desafiojackexpertsmari.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mari-app
                port:
                  number: 3001

---
apiVersion: v1
kind: Service
metadata:
  name: mari-app
  labels:
    app: mari-app
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: mari-app