apiVersion: apps/v1
kind: Deployment
metadata:
  name: mari-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mari-app  
  template:
    metadata:
      labels:
        app: mari-app
    spec:
      imagePullSecrets:
        - name: meu-secret-docker  # Adicionando o secret
      containers:
        - name: mari-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Usando a imagem do values.yaml
          ports:
            - containerPort: {{ .Values.service.port }}  # Usando a porta do values.yaml
          env:
            - name: PAGE_CONTENT
              value: {{ .Values.config.pageContent | quote }}  # Usando o conteúdo da página do values.yaml
            - name: USER_NAME
              value: {{ .Values.config.userName | quote }}  # Usando o nome de usuário do values.yaml
