apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mari-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: seu-domínio.com  # Coloque seu domínio aqui
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: mari-app
                port:
                  number: {{ .Values.service.port }}
