apiVersion: v1
kind: Service
metadata:
  name: mari-app
  labels:
    app: mari-app
spec:
  type: {{ .Values.service.type }}  # Tipo do serviço
  ports:
    - port: {{ .Values.service.port }}  # Porta exposta pelo serviço
      targetPort: {{ .Values.service.port }}  # Porta onde o aplicativo está escutando dentro do pod
      protocol: TCP
  selector:
    app: mari-app  # Seleciona os pods que correspondem ao label 'app: mari-app'
