users:
- name: arn:aws:eks:sa-east-1:396913734918:cluster/Projeto-jack-experts-Mari
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1  # Atualize aqui
      args:
      - --region
      - sa-east-1
      - eks
      - get-token
      - --cluster-name
      - Projeto-jack-experts-Mari
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
