users:
- name: arn:aws:eks:sa-east-1:396913734918:cluster/Projeto-jack-experts-Mari
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1  # Mude v1alpha1 para v1beta1
      args:
      - --region
      - sa-east-1
      - eks
      - get-token
      - --cluster-name
      - Projeto-jack-experts-Mari
      command: aws
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
- name: docker-desktop
  user:
    client-certificate-data: DATA+OMITTED
    client-key-data: DATA+OMITTED
