apiVersion: apps/v1
kind: Deployment
metadata:
  name: mari-app
  labels:
    app: mari-app
    desafio: jackexperts
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: mari-app
  template:
    metadata:
      labels:
        app: mari-app
    spec:
      containers:
        - name: mari-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PAGE_CONTENT
              valueFrom:
                configMapKeyRef:
                  name: mari-app-config
                  key: pageContent
