apiVersion : v1
kind: Service
metadata:
   name: mari-app
   labels:
     app: mari-app
     desafio: jackexperts
     
spec:
   type: {{.Values.service.type}}  
   ports:
     - port : {{.Values.service.port}}  
     targetPort: {{.Values.service.port}}

     selector:
       app: mari-app 