apiVersion: v1
kind: Config
clusters:
- name: Projeto-Jack-Experts
  cluster:
    server: https://9AD51B6B31191769BDB7BC81E9A923F7.sk1.sa-east-1.eks.amazonaws.com
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
users:
- name: arn:aws:eks:sa-east-1:396913734918:cluster/Projeto-Jack-Experts
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - --region
      - sa-east-1
      - eks
      - get-token
      - --cluster-name
      - Projeto-Jack-Experts
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
contexts:
- name: Projeto-Jack-Experts-context
  context:
    cluster: Projeto-Jack-Experts
    user: arn:aws:eks:sa-east-1:396913734918:cluster/Projeto-Jack-Experts
current-context: Projeto-Jack-Experts-context
